{% set version = '2.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gridextra
  version: {{ version|replace("-", "_") }}

source:
  fn: gridExtra_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/gridExtra_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/gridExtra/gridExtra_{{ version }}.tar.gz
  sha256: 81b60ce6f237ec308555471ae0119158b115463df696d2eca9b177ded8988e3b

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-gtable

  run:
    - r-base
    - r-gtable

test:
  commands:
    - $R -e "library('gridExtra')"  # [not win]
    - "\"%R%\" -e \"library('gridExtra')\""  # [win]

about:
  home: https://github.com/baptiste/gridextra
  license: GPL (>= 2)
  summary: Provides a number of user-level functions to work with "grid" graphics, notably to
    arrange multiple grid-based plots on a page, and draw tables.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
