appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Js2lN4y7u5uYbdocbLbyrBdg/uptXZCP7m5X+1vPQRKxS+jA/xC2chkfPATjcEvP+qpf7bbItX0ZJZCvTjJCHmybgcH81FLVqvvPPBkMH7hVUxqY8pwWe+z5lPfbfR4jSjLfy4J52/gQFYVoL8GDopx1wrDi0QYXCd6p5Jfe1nCOot9+FS6bHAwLBWQ4eNHEYsbWKer589bKtv9z1aBvxa54sF5e1dBqKpOlNet6YJlbsK4ujm4BM1xVA2+A+PMKVc1rjEjzwz/4dWSEmpF9cfI13/etNRikFDzTGl1/0MNplvb61UM07XIEVtmzTUCh8nrKg1q921kKyf3bs2hz6tvlVL+ke3rLxXU2Dxd6LMseuWfKqZ/lwGUmAYb2pwAwZxQv55BE1GEliet+GkA9xLa2kgZ31L0xgWMY6VfgLQRFakskCAfzKtYe9Dim62gWtBoqiSdg6p2L4C9JL79boOa7otfbg34PculdC3JAjDMSy/hx+ctDfqUPd5IGA50WPhXy+Y8/NnlDwJltkkMFod7limraToX9REB9cg0L7WUK4iFCW3Dkcb0oXeAzeWj+vW5tLI/14sVJAV4JMrQy5udSInu+glqrOU15oixdRY2xh5sd2IkSosfaLxIzj9mo/Wnrz3j7kWLfFjiN1d6QZGkk4aRujV2ka8LD3SRxKjE=}
